/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBudgetsIndexRouteImport } from './routes/_authenticated/budgets/index'
import { Route as AuthenticatedBudgetsPeriodIdRouteImport } from './routes/_authenticated/budgets/$periodId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetsIndexRoute =
  AuthenticatedBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBudgetsPeriodIdRoute =
  AuthenticatedBudgetsPeriodIdRouteImport.update({
    id: '/budgets/$periodId',
    path: '/budgets/$periodId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/budgets/$periodId': typeof AuthenticatedBudgetsPeriodIdRoute
  '/budgets/': typeof AuthenticatedBudgetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/budgets/$periodId': typeof AuthenticatedBudgetsPeriodIdRoute
  '/budgets': typeof AuthenticatedBudgetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/_authenticated/budgets/$periodId': typeof AuthenticatedBudgetsPeriodIdRoute
  '/_authenticated/budgets/': typeof AuthenticatedBudgetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/transactions'
    | '/wallets'
    | '/budgets/$periodId'
    | '/budgets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/transactions'
    | '/wallets'
    | '/budgets/$periodId'
    | '/budgets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/transactions'
    | '/_authenticated/wallets'
    | '/_authenticated/budgets/$periodId'
    | '/_authenticated/budgets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets/': {
      id: '/_authenticated/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AuthenticatedBudgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets/$periodId': {
      id: '/_authenticated/budgets/$periodId'
      path: '/budgets/$periodId'
      fullPath: '/budgets/$periodId'
      preLoaderRoute: typeof AuthenticatedBudgetsPeriodIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
  AuthenticatedBudgetsPeriodIdRoute: typeof AuthenticatedBudgetsPeriodIdRoute
  AuthenticatedBudgetsIndexRoute: typeof AuthenticatedBudgetsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
  AuthenticatedBudgetsPeriodIdRoute: AuthenticatedBudgetsPeriodIdRoute,
  AuthenticatedBudgetsIndexRoute: AuthenticatedBudgetsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
