version: "3.8"

services:
  # -------------------------------------------------------------
  # 1. SERVICE DATABASE (POSTGRESQL)
  # -------------------------------------------------------------
  postgres_db:
    image: postgres:15-alpine
    container_name: trello_postgres_container
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "trello"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trello_network

  # -------------------------------------------------------------
  # 2. SERVICE BACKEND (NESTJS)
  # -------------------------------------------------------------
  # nestjs_api:
  #   build:
  #     context: ./BE
  #     dockerfile: Dockerfile
  #   container_name: trello_nestjs_container
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #     # Tự động đọc các biến môi trường từ file .env ở máy thật
  #   env_file:
  #     - ./BE/.env
  #   environment:
  #     NODE_ENV: production
  #     # Ghi đè DATABASE_URL để NestJS kết nối tới container postgres_db thông qua mạng nội bộ Docker
  #     DATABASE_URL: postgresql://postgres:postgres@postgres_db:5432/trello
  #   # Đảm bảo database phải chạy trước thì app mới khởi động
  #   depends_on:
  #     - postgres_db
  #   networks:
  #     - trello_network

  # -------------------------------------------------------------
  # 3. PROMETHEUS (MONITORING))
  # -------------------------------------------------------------
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: trello_prometheus
  #   restart: always
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml # Gắn file cấu hình vào container
  #   ports:
  #     - "9090:9090" # Cổng giao diện của Prometheus
  #   networks:
  #     - trello_network
  #   depends_on:
  #     - nestjs_api

  # -------------------------------------------------------------
  # 4. SERVICE GRAFANA (Bộ hiển thị Dashboard)
  # -------------------------------------------------------------
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: trello_grafana
  #   restart: always
  #   ports:
  #     - "3001:3000" # Đổi cổng máy thật thành 3001 để tránh trùng cổng 3000 của NestJS
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   networks:
  #     - trello_network
  #   depends_on:
  #     - prometheus

# Định nghĩa Volume để lưu trữ data của Postgres (không bị mất data khi tắt container)
volumes:
  postgres_data:
  grafana_data: # Thêm volume để lưu cấu hình dashboard không bị mất khi tắt docker

# Định nghĩa Network nội bộ để 2 container kết nối được với nhau
networks:
  trello_network:
    driver: bridge
